### ISSUE TITLE
Error Message, "Rounding is necessary to represent the result of the operation at this scale."

### ISSUE THREAD

**Issue by danielstrum** [fuzionnz/nz.co.fuzion.extrafee#32]
After we migrated our site to a new server which is running PHP 8.1, we started getting this error when users select to add the extra fee. I see this below in the logs:
```
2024-06-23 20:15:26+0300  [debug] $backTrace = #0 /var/www/live/web/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(443): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/live/web/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(Brick\Math\Exception\RoundingNecessaryException))
#2 /var/www/live/web/wp-content/plugins/civicrm/civicrm.php(1231): CRM_Core_Invoke::invoke((Array:3))
#3 /var/www/live/web/wp-content/plugins/civicrm/includes/civicrm.basepage.php(425): CiviCRM_For_WordPress->invoke()
#4 /var/www/live/web/wp-includes/class-wp-hook.php(324): CiviCRM_For_WordPress_Basepage->basepage_handler(Object(WP))
#5 /var/www/live/web/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, (Array:1))
#6 /var/www/live/web/wp-includes/plugin.php(565): WP_Hook->do_action((Array:1))
#7 /var/www/live/web/wp-includes/class-wp.php(830): do_action_ref_array("wp", (Array:1))
#8 /var/www/live/web/wp-includes/functions.php(1336): WP->main("")
#9 /var/www/live/web/wp-blog-header.php(16): wp()
#10 /var/www/live/web/index.php(17): require("/var/www/live/web/wp-blog-header.php")
#11 {main}
```

**Comment by jitendrapurohit** [comment]
can you try this patch https://github.com/fuzionnz/nz.co.fuzion.extrafee/pull/31?
